In [17]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [18]:
data=pd.read_csv("datasets/Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [19]:
#information of data
data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [21]:
data = data.drop(data.columns[6:12], axis=1)

In [22]:
data.to_csv("datasets/updated_housing.csv", index=False)

In [23]:
data=pd.read_csv("datasets/updated_housing.csv")
data

        price  area  bedrooms  bathrooms  stories mainroad furnishingstatus
0    13300000  7420         4          2        3      yes        furnished
1    12250000  8960         4          4        4      yes        furnished
2    12250000  9960         3          2        2      yes   semi-furnished
3    12215000  7500         4          2        2      yes        furnished
4    11410000  7420         4          1        2      yes        furnished
..        ...   ...       ...        ...      ...      ...              ...
540   1820000  3000         2          1        1      yes      unfurnished
541   1767150  2400         3          1        1       no   semi-furnished
542   1750000  3620         2          1        1      yes      unfurnished
543   1750000  2910         3          1        1       no        furnished
544   1750000  3850         3          1        2      yes      unfurnished

[545 rows x 7 columns]

In [24]:
data=data.drop(data.columns[5:7],axis=1)

In [25]:
data

        price  area  bedrooms  bathrooms  stories
0    13300000  7420         4          2        3
1    12250000  8960         4          4        4
2    12250000  9960         3          2        2
3    12215000  7500         4          2        2
4    11410000  7420         4          1        2
..        ...   ...       ...        ...      ...
540   1820000  3000         2          1        1
541   1767150  2400         3          1        1
542   1750000  3620         2          1        1
543   1750000  2910         3          1        1
544   1750000  3850         3          1        2

[545 rows x 5 columns]

In [26]:
data.to_csv("datasets/updated_housing2.csv",index=False)

In [27]:
data= pd.read_csv("datasets/updated_housing2.csv")
data

        price  area  bedrooms  bathrooms  stories
0    13300000  7420         4          2        3
1    12250000  8960         4          4        4
2    12250000  9960         3          2        2
3    12215000  7500         4          2        2
4    11410000  7420         4          1        2
..        ...   ...       ...        ...      ...
540   1820000  3000         2          1        1
541   1767150  2400         3          1        1
542   1750000  3620         2          1        1
543   1750000  2910         3          1        1
544   1750000  3850         3          1        2

[545 rows x 5 columns]

In [28]:
# cleaning the data

In [29]:
reg=linear_model.LinearRegression()
reg.fit(data[['area','bedrooms','bathrooms','stories']], data.price)

LinearRegression()

In [30]:
reg.coef_

array([3.80024429e+02, 1.98295494e+05, 1.20018047e+06, 5.31595009e+05])

In [31]:
reg.intercept_

-282091.2903634589

In [32]:
#new way of do  so
features_names=['area','bedrooms','bathrooms','stories']
input_data=pd.DataFrame(np.array([[7420,4,2,3]]),columns=features_names)
price= reg.predict(input_data) 
print(price)

[7326017.9251189]